#!/bin/bash

#requirements install
pip install wandb
wandb login
pip install git+https://github.com/facebookresearch/text-simplification-evaluation.git
pip install transformers
#pip install -U pip setuptools wheel
#pip install setuptools==59.5.0
#pip install -U spacy
pip install git+https://github.com/PyTorchLightning/pytorch-lightning
pip install hydra-core --upgrade
python -m spacy download en_core_web_sm
#pip install torch==1.9+cu111  -f https://download.pytorch.org/whl/torch_stable.html

#exp_1
##no_aug
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=19zTe3z22GrX2jq-8wl-_8_PpFcZdn684' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=19zTe3z22GrX2jq-8wl-_8_PpFcZdn684" -O newsela_3more_dataframe_ext1_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1rlAXoNibMcuG8W5f4HCm-pCD9Z4RHRpz' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1rlAXoNibMcuG8W5f4HCm-pCD9Z4RHRpz" -O newsela_3more_dataframe_ext1_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1H3c7z01v1ctIwgVSp_G5_mMqQ4UTGFaV' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1H3c7z01v1ctIwgVSp_G5_mMqQ4UTGFaV" -O newsela_3more_dataframe_ext1_75.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Oa6vhlctajMxrmm9qwuNUFv3ysgKovzK' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Oa6vhlctajMxrmm9qwuNUFv3ysgKovzK" -O newsela_3more_dataframe_100.pickle && rm -rf /tmp/cookies.txt
##eo_seed=1
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1A8-taeW_E8fIK8czHdpa79cILMowOYmG' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1A8-taeW_E8fIK8czHdpa79cILMowOYmG" -O newsela_3more_dataframe_eo1_100.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1hFIvEQOyzSq4XtVK8nwoCeMNF4Lhymx9' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1hFIvEQOyzSq4XtVK8nwoCeMNF4Lhymx9" -O newsela_3more_dataframe_ext1_eo1_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1M36VJAy3mJ9whQYkisWxFnq8n6vaCkH3' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1M36VJAy3mJ9whQYkisWxFnq8n6vaCkH3" -O newsela_3more_dataframe_ext1_eo1_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1VHKSZVRKfXw__BhIkHcbNetuoMQ6L84Q' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1VHKSZVRKfXw__BhIkHcbNetuoMQ6L84Q" -O newsela_3more_dataframe_ext1_ro1_75.pickle && rm -rf /tmp/cookies.txt
##eo_seed=2
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=10tNznzZzpjAWR0YyFkqhGNXAwNL5R3_K' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=10tNznzZzpjAWR0YyFkqhGNXAwNL5R3_K" -O newsela_3more_dataframe_eo2_100.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=151fFyUi6Jl8634bVNAmU-CZ7R7OJ4d9g' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=151fFyUi6Jl8634bVNAmU-CZ7R7OJ4d9g" -O newsela_3more_dataframe_ext1_eo2_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1P4FwyyADCeEx1sLzLrzpcXntdHe2E4OQ' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1P4FwyyADCeEx1sLzLrzpcXntdHe2E4OQ" -O newsela_3more_dataframe_ext1_eo2_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1zZllkyZY3I3C6oJequJBl7P3XCVq6d3M' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1zZllkyZY3I3C6oJequJBl7P3XCVq6d3M" -O newsela_3more_dataframe_ext1_eo2_75.pickle && rm -rf /tmp/cookies.txt
##eo_seed=3
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1iKOKgcv0MA7I7zbIBQV2rO3JqBAMxWJA' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1iKOKgcv0MA7I7zbIBQV2rO3JqBAMxWJA" -O newsela_3more_dataframe_eo3_100.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1MsK69RLG3BRGjmgsRXPKWGkqR9EbhlOj' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1MsK69RLG3BRGjmgsRXPKWGkqR9EbhlOj" -O newsela_3more_dataframe_ext1_eo3_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1MjANWZJr5D-t0DvEwM5neY5xfbWevs3p' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1MjANWZJr5D-t0DvEwM5neY5xfbWevs3p" -O newsela_3more_dataframe_ext1_eo3_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Yw3uFSDCP5jIL_KS_RgPZsrF2_C1Hx3j' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Yw3uFSDCP5jIL_KS_RgPZsrF2_C1Hx3j" -O newsela_3more_dataframe_ext1_eo3_75.pickle && rm -rf /tmp/cookies.txt


#exp_2
##ext_seed=2
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1muwUdVv2SdRbW8SgSpgIoC9lflm9ehD-' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1muwUdVv2SdRbW8SgSpgIoC9lflm9ehD-" -O newsela_3more_dataframe_ext2_25.pickle && rm -rf /tmp/cookies.txt
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1pU0o0wyuZn9sQFg3-Mt7IAG6b8m3mc3_' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1pU0o0wyuZn9sQFg3-Mt7IAG6b8m3mc3_" -O newsela_3more_dataframe_ext2_50.pickle && rm -rf /tmp/cookies.txt
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1D6pC67XoXYnNWDWhPs9tKLF2PmSIvQyi' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1D6pC67XoXYnNWDWhPs9tKLF2PmSIvQyi" -O newsela_3more_dataframe_ext2_75.pickle && rm -rf /tmp/cookies.txt
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Rhd81yU3swmX6rtgg2YyoOExBGhlisGI' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Rhd81yU3swmX6rtgg2YyoOExBGhlisGI" -O newsela_3more_dataframe_ext2_eo1_25.pickle && rm -rf /tmp/cookies.txt
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1yUv0f40F2WDcUPM48lrhx9Fzwn9gK_vN' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1yUv0f40F2WDcUPM48lrhx9Fzwn9gK_vN" -O newsela_3more_dataframe_ext2_eo1_50.pickle && rm -rf /tmp/cookies.txt
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1euoPn9ryuqiq7mN255FpK-SsTc_qCFA0' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1euoPn9ryuqiq7mN255FpK-SsTc_qCFA0" -O newsela_3more_dataframe_ext2_eo1_75.pickle && rm -rf /tmp/cookies.txt
##ext_seed=3
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1txc0gn6v0XDwC4VBMz1ng1-f2QKTSdsZ' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1txc0gn6v0XDwC4VBMz1ng1-f2QKTSdsZ" -O newsela_3more_dataframe_ext3_25.pickle && rm -rf /tmp/cookies.txt
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=10HD-L1rOgyj5AiXmQGdG25Wffqt6lxtW' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=10HD-L1rOgyj5AiXmQGdG25Wffqt6lxtW" -O newsela_3more_dataframe_ext3_50.pickle && rm -rf /tmp/cookies.txt
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1PcCH8x2JAo3qAc0P-6E5l9J_k2DRf5u7' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1PcCH8x2JAo3qAc0P-6E5l9J_k2DRf5u7" -O newsela_3more_dataframe_ext3_75.pickle && rm -rf /tmp/cookies.txt
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1tuHpQv9SGTg29xqg7Q8PvJK5X_-7mRzU' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1tuHpQv9SGTg29xqg7Q8PvJK5X_-7mRzU" -O newsela_3more_dataframe_ext3_eo1_25.pickle && rm -rf /tmp/cookies.txt
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1l84Va-gFb5F_fvAP3R9ZvhoItTohRQ3p' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1l84Va-gFb5F_fvAP3R9ZvhoItTohRQ3p" -O newsela_3more_dataframe_ext3_eo1_50.pickle && rm -rf /tmp/cookies.txt
#wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1xzdWOsHtfiUetCpXckHaB9izKrg5pooC' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1xzdWOsHtfiUetCpXckHaB9izKrg5pooC" -O newsela_3more_dataframe_ext3_eo1_75.pickle && rm -rf /tmp/cookies.txt

#move files
mv n* ../../data