wandb:
  project: newsela_only_v5_exp1
  exp_num: 1
  tags: [bert]
path:
  #exp1
  ##25% (exp_num=1)
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext1_25.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext2_25.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext3_25.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext4_25.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext5_25.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext6_25.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext7_25.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext8_25.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext9_25.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext10_25.pickle
  ##50% (exp_num=2)
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext1_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext2_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext3_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext4_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext5_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext6_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext7_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext8_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext9_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext10_50.pickle
  ##75% (exp_num=3)
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext1_75.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext2_75.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext3_75.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext4_75.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext5_75.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext6_75.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext7_75.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext8_75.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext9_75.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_ext10_75.pickle
  ##100% (exp_num=4)
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_no_aug_100.pickle

  #exp_2 (100%)
  ##+50
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_aug1_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_aug2_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_aug3_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_aug4_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_aug5_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_aug6_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_aug7_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_aug8_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_aug9_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_aug10_50.pickle
  ##+100
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_only_100.pickle

  checkpoint_path: checkpoints
model:
  n_classes: 1
  dropout_rate: 0.2
  max_token_len: 512
  pooling_type: cls
  added_feature_num: 0
training:
  pl_seed: 1
  test_size: 0.3
  valid_size: 0.3
  n_epochs: 5
  batch_size: 16
  learning_rate: 0.0001
  n_gpus: 1

callbacks:
  patience: 3
  patience_min_delta: 0