wandb:
  project: newsela_v11_nprm_filtered_50_exp2
  exp_num: 21
  tags: [bert]
path:
  #exp_2 gold (expnum=2)
  ##m=1 
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_gold_filtered_m1aug1_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_gold_filtered_m1aug2_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_gold_filtered_m1aug3_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_gold_filtered_m1aug4_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_gold_filtered_m1aug5_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_gold_filtered_m1aug6_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_gold_filtered_m1aug7_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_gold_filtered_m1aug8_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_gold_filtered_m1aug9_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_gold_filtered_m1aug10_50.pickle

  #exp_2 silver (expnum=3)
  ##m=1
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_silver_filtered_m1aug1_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_silver_filtered_m1aug2_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_silver_filtered_m1aug3_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_silver_filtered_m1aug4_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_silver_filtered_m1aug5_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_silver_filtered_m1aug6_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_silver_filtered_m1aug7_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_silver_filtered_m1aug8_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_silver_filtered_m1aug9_50.pickle
  #data_file_name: /workspace/simpeval/marginranking/newsela/data/newsela_nprm_v11_silver_filtered_m1aug10_50.pickle

#===================================================================================================================================
  
  checkpoint_path: checkpoints
model:
  n_classes: 2
  dropout_rate: 0.2
  max_token_len: 512
  pooling_type: cls
  added_feature_num: 0
training:
  pl_seed: 1
  #test_size: 0.3
  valid_size: 0.2
  n_epochs: 10
  batch_size: 16
  learning_rate: 0.0001
  n_gpus: 1

callbacks:
  patience: 3
  patience_min_delta: 0