#!/bin/bash

#requirements install
pip install wandb
wandb login
pip install git+https://github.com/facebookresearch/text-simplification-evaluation.git
pip install transformers
#pip install -U pip setuptools wheel
#pip install setuptools==59.5.0
#pip install -U spacy
pip install git+https://github.com/PyTorchLightning/pytorch-lightning
pip install hydra-core --upgrade
python -m spacy download en_core_web_sm
#pip install torch==1.9+cu111  -f https://download.pytorch.org/whl/torch_stable.html

#exp_1
##25%
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1qCASeu22vwFYuR_BA3BMZeGkG18EuDYT' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1qCASeu22vwFYuR_BA3BMZeGkG18EuDYT" -O newsela_3more_dataframe_ext1_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1aUZys62aVPUnuIgqjimetpeLWC3Cmtom' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1aUZys62aVPUnuIgqjimetpeLWC3Cmtom" -O newsela_3more_dataframe_ext2_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1xt0DSqDSNNkss7sih4zd8WcyvAF-biYb' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1xt0DSqDSNNkss7sih4zd8WcyvAF-biYb" -O newsela_3more_dataframe_ext3_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1cJZE8X0CI5GH4iypP2IzA7wiJREDH28b' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1cJZE8X0CI5GH4iypP2IzA7wiJREDH28b" -O newsela_3more_dataframe_ext4_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1LCZRwMHpeAdqSmbwLcjkln5gors5fDaU' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1LCZRwMHpeAdqSmbwLcjkln5gors5fDaU" -O newsela_3more_dataframe_ext5_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1BTrKSf9BH3uK7j9JlOEyL6kN58BnUONo' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1BTrKSf9BH3uK7j9JlOEyL6kN58BnUONo" -O newsela_3more_dataframe_ext6_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Mit3zAvmgKMdQZ7hMBz7UHH19TUfv89v' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Mit3zAvmgKMdQZ7hMBz7UHH19TUfv89v" -O newsela_3more_dataframe_ext7_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1qtp3JQHSdlIs4i4KFw9ThWvMY45jV-Uy' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1qtp3JQHSdlIs4i4KFw9ThWvMY45jV-Uy" -O newsela_3more_dataframe_ext8_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1GFicFloR3lNvu4QAQ0BsubVR-Aufz-bt' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1GFicFloR3lNvu4QAQ0BsubVR-Aufz-bt" -O newsela_3more_dataframe_ext9_25.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1pgD0tln86yi2VPi8ScXHdFos20nB2T7L' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1pgD0tln86yi2VPi8ScXHdFos20nB2T7L" -O newsela_3more_dataframe_ext10_25.pickle && rm -rf /tmp/cookies.txt
##50%
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1JAC2dx9wzj_bb5ego3SBAbdsV1Rltn1a' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1JAC2dx9wzj_bb5ego3SBAbdsV1Rltn1a" -O newsela_3more_dataframe_ext1_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1K0_cTnnUn8wrlLxS5ih-zsp5uwns7C-6' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1K0_cTnnUn8wrlLxS5ih-zsp5uwns7C-6" -O newsela_3more_dataframe_ext2_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=163fd6RcRhU_1R0V_rqQg8llO8-8qDEil' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=163fd6RcRhU_1R0V_rqQg8llO8-8qDEil" -O newsela_3more_dataframe_ext3_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1WJsLgv39eks25GTEAKR3QykikdplMS76' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1WJsLgv39eks25GTEAKR3QykikdplMS76" -O newsela_3more_dataframe_ext4_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1KgihNSLUum0vKawYbOZWBQeRzcvvL-mD' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1KgihNSLUum0vKawYbOZWBQeRzcvvL-mD" -O newsela_3more_dataframe_ext5_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1gQ0rQ8gT9E6uEJ5kZq6j54UYL9nN8p79' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1gQ0rQ8gT9E6uEJ5kZq6j54UYL9nN8p79" -O newsela_3more_dataframe_ext6_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1wBlB05dIvoOLPjpC4uW_hmEibEpCJXEj' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1wBlB05dIvoOLPjpC4uW_hmEibEpCJXEj" -O newsela_3more_dataframe_ext7_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1nEGTAPhzG0tqVR_CfyOOZ4RLPq3eBRjI' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1nEGTAPhzG0tqVR_CfyOOZ4RLPq3eBRjI" -O newsela_3more_dataframe_ext8_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1N_k0cg_rKyGS3SlXkyaK-jvmnOXgYd8y' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1N_k0cg_rKyGS3SlXkyaK-jvmnOXgYd8y" -O newsela_3more_dataframe_ext9_50.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1DEbCD88JPCfGl_mWpQuBqCqwPJTmUxjG' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1DEbCD88JPCfGl_mWpQuBqCqwPJTmUxjG" -O newsela_3more_dataframe_ext10_50.pickle && rm -rf /tmp/cookies.txt
##75%
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1g7SoqBlbHM-n9XikrTG-CdsLltHM7jli' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1g7SoqBlbHM-n9XikrTG-CdsLltHM7jli" -O newsela_3more_dataframe_ext1_75.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1n_5uVohptQOOOQ9jqJJq117IbmbvoN0q' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1n_5uVohptQOOOQ9jqJJq117IbmbvoN0q" -O newsela_3more_dataframe_ext2_75.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1w-9-fbjv6m6uiuvjESidK8HkaiTEHoKc' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1w-9-fbjv6m6uiuvjESidK8HkaiTEHoKc" -O newsela_3more_dataframe_ext3_75.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1b4SWoT5_UxhZ68iz_DlsFmkIDLWwelLQ' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1b4SWoT5_UxhZ68iz_DlsFmkIDLWwelLQ" -O newsela_3more_dataframe_ext4_75.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=18IqkquT25lEnc_rK3L6y-RTah6hiQ0ra' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=18IqkquT25lEnc_rK3L6y-RTah6hiQ0ra" -O newsela_3more_dataframe_ext5_75.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=11oa1R0JYUrooUwp17KO5YuKABgP8hpeb' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=11oa1R0JYUrooUwp17KO5YuKABgP8hpeb" -O newsela_3more_dataframe_ext6_75.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1DCLynS87IfhjzXmhBompfFxWAbz0ITKC' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1DCLynS87IfhjzXmhBompfFxWAbz0ITKC" -O newsela_3more_dataframe_ext7_75.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1WgyrLUyPL5B6Sgzfvt5EcpXGZKAB3Dt5' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1WgyrLUyPL5B6Sgzfvt5EcpXGZKAB3Dt5" -O newsela_3more_dataframe_ext8_75.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1AzwtgEcqrstXrV51bqgfQz68Dgsgu-AJ' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1AzwtgEcqrstXrV51bqgfQz68Dgsgu-AJ" -O newsela_3more_dataframe_ext9_75.pickle && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1TAKe99e-Kv6qc4G8BUl_-tdX17oZQuWY' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1TAKe99e-Kv6qc4G8BUl_-tdX17oZQuWY" -O newsela_3more_dataframe_ext10_75.pickle && rm -rf /tmp/cookies.txt
##100%
wget --load-cookies /tmp/cookies.txt "https://drive.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://drive.google.com/uc?export=download&id=1ctiVWwGscQ6swBLFi9NXH2mgxzfM7tBM' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1ctiVWwGscQ6swBLFi9NXH2mgxzfM7tBM" -O newsela_3more_dataframe_100.pickle && rm -rf /tmp/cookies.txt
#move files
mv n* ../../data