wandb:
  project: wikiauto_marginranking_addfeatures
  exp_num: 1
  tags: [bert]
path:
  #random_sampled_data_labeled: /workspace/simpeval/marginranking/wikiauto/data/random_sampled_df_labeled_max_cnt_6_randomsamp_16.pickle
  #random_sampled_data_unlabeled: /workspace/simpeval/marginranking/wikiauto/data/random_sampled_df_unlabeled_max_cnt_6_randomsamp_16.pickle
  #aug_data: /workspace/simpeval/marginranking/wikiauto/data/augmented_wikiauto_max_cnt_6.pickle
  #sources: /workspace/simpeval/marginranking/wikiauto/data/wikiauto_sources.pickle
  #targets: /workspace/simpeval/marginranking/wikiauto/data/wikiauto_targets.pickle
  #finetuned: /workspace/simpeval/marginranking/wikiauto/data/epoch=9.ckpt
  #raw_predicted_path: /workspace/simpeval/marginranking/wikiauto/data/raw_predicted_wikiauto_max_cnt_6_randomsamp_16_labeled_by_exp_1.pickle
  data_file_name: /workspace/simpeval/marginranking/wikiauto/data/wikiauto_dataframe_addfeatures.pickle
  checkpoint_path: checkpoints
model:
  n_classes: 1
  n_linears: 1
  d_hidden_linear: 128
  dropout_rate: 0.2
  max_token_len: 512
  pooling_type: cls
  #pooling_type: cls_meanpooled
  #pooling_type: max
  #pooling_type: 4_cls
  added_feature_num: 0
training:
  pl_seed: 1
  test_size: 0.3
  valid_size: 0.3
  n_epochs: 10
  batch_size: 128
  learning_rate: 0.05
  n_gpus: 1
  #origin_column_namr: origin
  #orig_column_name: original
  #simp_column_name: simple
  #wordrank_score_name: wordrank_score
  #wordrank_score_orig_name: wordrank_score_orig
  #syllables_per_word_name: syllables_per_word
  #syllables_per_word_orig_name: syllables_per_word_orig
  #comp_ratio_name: comp_ratio
  #deleted_words_prop_name: deleted_words_prop
  #added_words_prop_name: added_words_prop
  #reordered_words_prop_name: reordered_words_prop
  #edit_sequences_len_name: edit_sequences_len
  #rep_operation_nums_name: rep_operation_nums
  #ad_operation_nums_name: ad_operation_nums
  #splr_operation_nums_name: splr_operation_nums
  #mvr_operation_nums_name: mvr_operation_nums
  #d_operation_nums_name: d_operation_nums
  #a_operation_nums_name: a_operation_nums
  #comp_ratio_orig_name: comp_ratio_orig
  #deleted_words_prop_orig_name: deleted_words_prop_orig
  #added_words_prop_orig_name: added_words_prop_orig
  #reordered_words_prop_orig_name: reordered_words_prop_orig
  #edit_sequences_len_orig_name: edit_sequences_len_orig
  #rep_operation_nums_orig_name: rep_operation_nums_orig
  #ad_operation_nums_orig_name: ad_operation_nums_orig
  #splr_operation_nums_orig_name: splr_operation_nums_orig
  #mvr_operation_nums_orig_name: mvr_operation_nums_orig
  #d_operation_nums_orig_name: d_operation_nums_orig
  #a_operation_nums_orig_name: a_operation_nums_orig
  #label_column_name: label
  #case_num_column_name: case_number
#dataprep:
#  n_random_sample: 16
#  random_seed: 0
#  batch_size: 64
#  max_token_len: 512
#  n_linears: 1
#  d_hidden_linear: 128
#  dropout_rate: 0.2


callbacks:
  patience: 5
  patience_min_delta: 0
